Repository hpc-io/h5bench, pull requests merged in 2021-07, with the labels that each got.

#6 Upgrades on h5bench
  CMakeLists.txt
  README.md
  commons/async_adaptor.h
  commons/h5bench_util.c
  docs/source/exerciser.rst
  docs/source/suiteusage.rst
  exerciser/h5bench_exerciser.c
  h5bench_patterns/h5bench_read.c
  h5bench_patterns/h5bench_write.c
  h5bench_patterns/metalist_cori.txt
  h5bench_patterns/metalist_summit.txt
  h5bench_patterns/sample_config/sample_2d_compressed.cfg
  h5bench_patterns/sample_config/sample_read_cc1d.cfg
  h5bench_patterns/sample_config/sample_read_cc1d_es1.cfg
  h5bench_patterns/sample_config/sample_read_cc2d.cfg
  h5bench_patterns/sample_config/sample_read_strided.cfg
  h5bench_patterns/sample_config/sample_write_cc1d.cfg
  h5bench_patterns/sample_config/sample_write_cc1d_es1.cfg
  h5bench_patterns/sample_config/sample_write_cc1d_fileperproc.cfg
  h5bench_patterns/sample_config/sample_write_cc2d.cfg
  h5bench_patterns/sample_config/sample_write_strided.cfg
  h5bench_patterns/sample_config/template.cfg
  metadata_stress/hdf5_iotest.c
Labels: bug, documentation, enhancement

#7 Include logo and update documentation
  README.md
  docs/source/buildinstructions.rst
  docs/source/conf.py
  docs/source/contents.rst
  docs/source/images/h5bench-logo.png
  docs/source/sampleconfigs.rst
  docs/source/suiteusage.rst
Labels: documentation

#8 Update documentation for MPI_THREAD_MULTIPLE
  docs/source/suiteusage.rst
Labels: documentation

#11 Update h5bench_read.c
  h5bench_patterns/h5bench_read.c
Labels: bug

#10 This closes #9
  commons/h5bench_util.c
Labels: bug

#12 fix for hdf5 v1.12.1 where _H5ESpublic_H became H5ESpublic_H
  commons/async_adaptor.h
Labels: bug

#15 Remove operation from configuration file and fix for HDF5 1.8
  .github/workflows/linux.yml
  .gitlab-ci.yml
  h5bench_patterns/h5bench_read.c
  h5bench_patterns/h5bench_write.c
  h5bench_patterns/sample_config/sample_2d_compressed.cfg
  h5bench_patterns/sample_config/sample_cc1d_small.cfg
  h5bench_patterns/sample_config/sample_cc1d_small_EXP.cfg
  h5bench_patterns/sample_config/sample_cc1d_small_IMP.cfg
  h5bench_patterns/sample_config/sample_read_cc1d.cfg
  h5bench_patterns/sample_config/sample_read_cc1d_es1.cfg
  h5bench_patterns/sample_config/sample_write_cc1d.cfg
  h5bench_patterns/sample_config/sample_write_cc1d_small.cfg
  h5bench_patterns/sample_config/template.cfg
Labels: bug
