Repository hpc-io/h5bench, pull requests merged in 2022-04, with the labels that each got.

#49 Update CSV output format
  commons/h5bench_util.c
  commons/h5bench_util.h
  h5bench_patterns/h5bench_append.c
  h5bench_patterns/h5bench_overwrite.c
  h5bench_patterns/h5bench_read.c
  h5bench_patterns/h5bench_write.c
  h5bench_patterns/h5bench_write_unlimited.c
Labels: enhancement

#50 Update documentation and Spack instructions
  docs/source/buildinstructions.rst
Labels: documentation

#52 Create .gitignore
  .gitignore
Labels: enhancement

#56 Fixes #55
  h5bench_patterns/h5bench_read.c
Labels: bug

#51 Improve return codes and failed checks and fix VOL-ASYNC integration
  .github/workflows/h5bench-hdf5-1.10.4.yml
  .github/workflows/h5bench-hdf5-1.10.7.yml
  .github/workflows/h5bench-hdf5-1.10.8.yml
  .github/workflows/h5bench-hdf5-1.12.0.yml
  .github/workflows/h5bench-hdf5-1.13.0-mpich-3.4.3.yml
  .github/workflows/h5bench-hdf5-1.13.0.yml
  .github/workflows/h5bench-hdf5-develop.yml
  CMakeLists.txt
  commons/h5bench_util.c
  h5bench
  h5bench_patterns/h5bench_append.c
  h5bench_patterns/h5bench_overwrite.c
  h5bench_patterns/h5bench_read.c
  h5bench_patterns/h5bench_write.c
  h5bench_patterns/h5bench_write_unlimited.c
  samples/sync-overwrite.json
  samples/update.py
Labels: bug, enhancement

#54 Correct use of H5Sselect_hyperslab
  h5bench_patterns/h5bench_append.c
  h5bench_patterns/h5bench_overwrite.c
  h5bench_patterns/h5bench_read.c
  h5bench_patterns/h5bench_write.c
  h5bench_patterns/h5bench_write_unlimited.c
Labels: bug
