Repository hpc-io/h5bench, pull requests merged in 2023-05, with the labels that each got.

#97 This fixes #91, #92, #93, #94, and #95
  .github/workflows/h5bench-hdf5-1.10.4.yml
  .github/workflows/h5bench-hdf5-1.10.7.yml
  .github/workflows/h5bench-hdf5-1.10.8.yml
  exerciser/h5bench_exerciser.c
  samples/sync-exerciser.json
  src/h5bench.py
Labels: bug

#98 Fix samples parameter
  samples/async-amrex.json
  samples/async-write-1d-contig-contig-gpfs-align.json
  samples/async-write-1d-contig-contig-read-full.json
  samples/async-write-1d-contig-contig-read-partial.json
  samples/async-write-1d-contig-contig-read-strided.json
  samples/async-write-1d-contig-contig.json
  samples/async-write-1d-contig-interleaved.json
  samples/async-write-1d-contig-strided.json
  samples/async-write-1d-interleaved-contig.json
  samples/async-write-1d-interleaved-interleaved.json
  samples/async-write-2d-contig-contig-read-full.json
  samples/async-write-2d-contig-contig.json
  samples/async-write-2d-contig-interleaved.json
  samples/async-write-2d-interleaved-contig.json
  samples/async-write-2d-interleaved-interleaved.json
  samples/async-write-3d-contig-contig-read-full.json
  samples/async-write-3d-contig-contig.json
  samples/sync-exerciser.json
  samples/sync-metadata.json
  samples/sync-write-1d-contig-contig-read-full.json
  samples/sync-write-1d-contig-contig-read-partial.json
  samples/sync-write-1d-contig-contig-read-strided.json
  samples/sync-write-1d-contig-contig.json
  samples/sync-write-1d-contig-interleaved.json
  samples/sync-write-1d-contig-strided.json
  samples/sync-write-1d-interleaved-contig.json
  samples/sync-write-1d-interleaved-interleaved.json
  samples/sync-write-2d-contig-contig-read-full.json
  samples/sync-write-2d-contig-contig.json
  samples/sync-write-2d-contig-interleaved.json
  samples/sync-write-2d-interleaved-contig.json
  samples/sync-write-2d-interleaved-interleaved.json
  samples/sync-write-3d-contig-contig-read-full.json
  samples/sync-write-3d-contig-contig.json
  samples/sync-write-contig-interleaved.json
Labels: tests

#75 added missing read csv information
  h5bench_patterns/h5bench_read.c
Labels: enhancement

#101 This closes #84 by updating docs with subfiling options
  docs/source/vpic.rst
Labels: documentation

#102 Removing deprecated configuration files
  h5bench_patterns/sample_config/sample_2d_compressed.cfg
  h5bench_patterns/sample_config/sample_append.cfg
  h5bench_patterns/sample_config/sample_cc1d_small.cfg
  h5bench_patterns/sample_config/sample_cc1d_small_EXP.cfg
  h5bench_patterns/sample_config/sample_cc1d_small_IMP.cfg
  h5bench_patterns/sample_config/sample_overwrite_cc1d.cfg
  h5bench_patterns/sample_config/sample_read_cc1d.cfg
  h5bench_patterns/sample_config/sample_read_cc1d_es1.cfg
  h5bench_patterns/sample_config/sample_read_cc2d.cfg
  h5bench_patterns/sample_config/sample_read_strided.cfg
  h5bench_patterns/sample_config/sample_write_cc1d.cfg
  h5bench_patterns/sample_config/sample_write_cc1d_es1.cfg
  h5bench_patterns/sample_config/sample_write_cc1d_fileperproc.cfg
  h5bench_patterns/sample_config/sample_write_cc1d_small_EXP.cfg
  h5bench_patterns/sample_config/sample_write_cc1d_small_IMP.cfg
  h5bench_patterns/sample_config/sample_write_cc2d.cfg
  h5bench_patterns/sample_config/sample_write_strided.cfg
  h5bench_patterns/sample_config/sample_write_unlimited.cfg
  h5bench_patterns/sample_config/template.cfg
Labels: enhancement
