Repository hpc-io/h5bench, pull requests merged in 2023-07, with the labels that each got.

#109 Update CI with additional flag for ASYNC VOL
  .github/workflows/h5bench-hdf5-1.10.4.yml
  .github/workflows/h5bench-hdf5-1.10.7.yml
  .github/workflows/h5bench-hdf5-1.10.8.yml
  .github/workflows/h5bench-hdf5-1.12.0.yml
  .github/workflows/h5bench-hdf5-1.13.0.yml
  .github/workflows/h5bench-hdf5-1.14.0.yml
  .github/workflows/h5bench-hdf5-1.14.1.yml
  .github/workflows/h5bench-hdf5-develop-test.yml
  .github/workflows/h5bench-hdf5-develop.yml
  CMakeLists.txt
Labels: bug

#108 Update build instructions with HDF5 information
  docs/source/buildinstructions.rst
Labels: documentation

#106 Closes #105 by updating build instruction for MacOS
  docs/source/buildinstructions.rst
Labels: documentation

#88 Added support for writing varying local data size in each process
  CMakeLists.txt
  commons/h5bench_util.c
  commons/h5bench_util.h
  docs/source/vpic.rst
  h5bench_patterns/h5bench_write_normal_dist.c
  samples/sync-write-1d-contig-contig-normal-dist.json
  src/h5bench.py
  tests/test_sync_h5bench_normal_dist.py
Labels: enhancement, new benchmark
